# Generated by Django 5.1.7 on 2025-05-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10)),
                ('idade', models.IntegerField()),
                ('identidade', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=50)),
                ('flexoes', models.IntegerField()),
                ('abdominais', models.IntegerField()),
                ('corrida', models.IntegerField()),
                ('nivel_flexoes', models.CharField(max_length=10)),
                ('nivel_abdominais', models.CharField(max_length=10)),
                ('nivel_corrida', models.CharField(max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
